# helpers.py
# DO NOT EDIT THIS FILE.
# It is downloaded automatically by the notebook and used for setup utilities.

from __future__ import annotations

from typing import Any, Dict, List

def load_example_dataset() -> List[Dict[str, Any]]:
    """Return the small example dataset used throughout the Day 1 notebook."""
    return [
        {
            "id": 1,
            "name": "Arianna",
            "age": 18,
            "favorite_artist": "Lazza",
            "daily_music_minutes": 90,
            "hobbies": ["gym", "gaming"],
        },
        {
            "id": 2,
            "name": "Marco",
            "age": 19,
            "favorite_artist": "Billie Eilish",
            "daily_music_minutes": 40,
            "hobbies": ["football", "cinema"],
        },
        {
            "id": 3,
            "name": "Giulia",
            "age": 18,
            "favorite_artist": "Sfera Ebbasta",
            "daily_music_minutes": 120,
            "hobbies": ["drawing", "reading"],
        },
    ]

def dataset_to_csv_text(people: List[Dict[str, Any]]) -> str:
    """
    Convert dataset to CSV text. Lists are encoded as ';'-separated strings.
    This keeps the CSV demonstration focused on the tradeoff: CSV is tabular,
    but struggles with nested/list fields.
    """
    import csv
    import io

    output = io.StringIO()
    writer = csv.DictWriter(
        output,
        fieldnames=["id", "name", "age", "favorite_artist", "daily_music_minutes", "hobbies"],
    )
    writer.writeheader()

    for p in people:
        row = dict(p)
        hobbies = row.get("hobbies", [])
        if isinstance(hobbies, list):
            row["hobbies"] = ";".join(str(x) for x in hobbies)
        writer.writerow(row)

    return output.getvalue()

def csv_text_to_rows(csv_text: str) -> List[Dict[str, str]]:
    """Parse CSV text into a list of dict rows (values are strings, per CSV)."""
    import csv
    import io

    buf = io.StringIO(csv_text)
    reader = csv.DictReader(buf)
    return list(reader)
